language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
    - shellcheck -e SC2034 -e SC2166 duplicity-backup.sh duplicity-backup.conf.example

matrix:
  fast_finish: true
